import React from 'react'
import "./Home.css"
import Testimonies from '../../component/testimonies/Testimonies'




export default function Home() {

  return (
    <>

      <div className='row1'>
        <div>
    <h1 className='mainH1'>Create your<br /> 
     winning resume <br /> 
    in just 15 minutes</h1>

    <button >BUILD MY RESUME</button>
    </div>
    <div>
      <img className='homeImg' src="https://thehubbackend.com/media/job-search.jpg" alt="" />
    </div>
    </div>


    <div className='row2'>
      <h2 className='homeHeadLine'>Get your professional resume in 3 steps</h2>

        <div className='boxRow2'>

      <div className='imgBox'>
        <img className='img' src="https://static.resumecoach.com/wp-content/uploads/sites/43/2024/01/11112535/1_choose_ATS.png" alt="" />
        <p>Choose a template optimized for ATS</p>
      </div>

      <div className='imgBox'>
        <img className='img' src="https://static.resumecoach.com/wp-content/uploads/sites/43/2024/01/11112537/2_AI.png" alt="" />
        <p>Complete with phrases generated by the assistant</p>
      </div>

      <div className='imgBox'>
        <img className='img' src="https://static.resumecoach.com/wp-content/uploads/sites/43/2024/01/11112538/3_download.png" alt="" />
        <p>Provide the right format, download, and send</p>
      </div>
      
      </div>
     
      <button>CREATE MY RESUME</button>
      </div>

      <div className='row3'>
        <Testimonies/>

      </div>

      <div className='row4'>
      <a href="tel:+972503135340">call me</a>


      </div>





    

  

    
    </>
  )
}
